global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'microservices'
    static_configs:
      - targets: 
          - 'frontend:80'
          - 'link-service:3000'
          - 'analytics-service:4000'
