version: '3.8'

services:
  frontend:
    image: am12344/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - link-service
      - analytics-service

  link-service:
    image: am12344/link-service:latest
    ports:
      - "3000:3000"  # Crucial: Opens port for Prometheus to scrape
    environment:
      - SERVICE_NAME=link-service

  analytics-service:
    image: am12344/analytics-service:latest
    ports:
      - "4000:4000"  # Crucial: Opens port for Prometheus to scrape
    environment:
      - SERVICE_NAME=analytics-service

  # --- MONITORING STACK ---
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - link-service
      - analytics-service

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Default login for your evaluator
    depends_on:
      - prometheus
