version: '3.8'

services:
  frontend:
    image: am12344/frontend:latest
    ports:
      - "80:80"
    environment:
      - SERVICE_NAME=frontend

  link-service:
    image: am12344/link-service:latest
    environment:
      - SERVICE_NAME=link-service

  analytics-service:
    image: am12344/analytics-service:latest
    environment:
      - SERVICE_NAME=analytics-service

  # --- MONITORING STACK ---
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
